# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=/snap/android-studio/225/jbr
org.gradle.java.installations.paths=/snap/android-studio/225/jbr
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
