apply plugin: 'com.android.application'

android {
    namespace 'cn.zhengweiyi.weiyichild'
    compileSdk 36
    buildToolsVersion "37.0.0"

    defaultConfig {
        applicationId "cn.zhengweiyi.weiyichild"
        minSdk 21
        targetSdk 34
        versionCode 4
        versionName "1.1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.preference:preference:1.2.1'

    implementation 'com.github.yuzhiqiang1993:zxing:2.2.7'
    implementation 'com.yanzhenjie:permission:2.0.2'    //引入 AndPermission 进行权限管理
    implementation project(':calendarview')             //引入 CalendarView 日历控件（https://github.com/huanghaibin-dev/CalendarView）
    implementation 'androidx.room:room-runtime:2.6.1'   //引入 Room 数据库
    annotationProcessor 'androidx.room:room-compiler:2.6.1'  //Room 注解处理器

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
}
