package cn.zhengweiyi.weiyichild.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.zhengweiyi.weiyichild.bean.Dietary;

import cn.zhengweiyi.weiyichild.greenDao.db.DietaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dietaryDaoConfig;

    private final DietaryDao dietaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dietaryDaoConfig = daoConfigMap.get(DietaryDao.class).clone();
        dietaryDaoConfig.initIdentityScope(type);

        dietaryDao = new DietaryDao(dietaryDaoConfig, this);

        registerDao(Dietary.class, dietaryDao);
    }
    
    public void clear() {
        dietaryDaoConfig.clearIdentityScope();
    }

    public DietaryDao getDietaryDao() {
        return dietaryDao;
    }

}
