package cn.zhengweiyi.weiyichild.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.zhengweiyi.weiyichild.bean.PickupHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICKUP_HISTORY".
*/
public class PickupHistoryDao extends AbstractDao<PickupHistory, Long> {

    public static final String TABLENAME = "PICKUP_HISTORY";

    /**
     * Properties of entity PickupHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, java.util.Date.class, "date", false, "DATE");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property Parent = new Property(3, String.class, "parent", false, "PARENT");
        public final static Property Teacher = new Property(4, String.class, "teacher", false, "TEACHER");
    }


    public PickupHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public PickupHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICKUP_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DATE\" INTEGER," + // 1: date
                "\"TYPE\" TEXT," + // 2: type
                "\"PARENT\" TEXT," + // 3: parent
                "\"TEACHER\" TEXT);"); // 4: teacher
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICKUP_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PickupHistory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String parent = entity.getParent();
        if (parent != null) {
            stmt.bindString(4, parent);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(5, teacher);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PickupHistory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String parent = entity.getParent();
        if (parent != null) {
            stmt.bindString(4, parent);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(5, teacher);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PickupHistory readEntity(Cursor cursor, int offset) {
        PickupHistory entity = new PickupHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // parent
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // teacher
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PickupHistory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParent(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTeacher(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PickupHistory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PickupHistory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PickupHistory entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
